<a href="https://colab.research.google.com/github/DipeshPun/ML/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Numpy
Creating an array.✅
Multidimenisional array.✅
Randomly generated arrays.✅
Element wise operation.
Summerizing operations.

##Single Dimensional array

In [19]:
import numpy as np

In [20]:
#cate an array with all the elements to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
#creating an array of ones
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
#create an array of sixe 10 with all elements:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [23]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [24]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [25]:
#Create an array with evenly spaced numbers within a specified range:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi Dimensional array


In [26]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
z=np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
z[0,1]=20
print(z)

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


In [28]:
#z[2:3]=1
z[2]=[1, 1, 1]
z

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [29]:
z[:,2]=[2, 2, 2]
z

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [30]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## Randomly generated array
Numpy can create arrays dilled with random numbers
To ensure the reproductibility, you cab set a seed using ``np.random.seed()``, It will generate the exact same random numbers for each executions.
If you remove or change the seed values, the sequence of randim numbers will be changed.

In [31]:
np.random.rand(10)

array([0.67941112, 0.65078591, 0.26879524, 0.06732467, 0.77144514,
       0.48098413, 0.32920641, 0.51064106, 0.26362883, 0.31051155])

In [32]:
np.random.seed(20)
np.random.rand(5)

array([0.5881308 , 0.89771373, 0.89153073, 0.81583748, 0.03588959])

In [33]:
np.random.randn(5, 2)

array([[-0.95044312,  1.50227571],
       [ 2.12601055,  0.24915543],
       [-0.62064216, -0.83453294],
       [ 0.91635593,  0.70783847],
       [ 0.41967613,  0.53415759]])

In [34]:
np.random.randint(low=0, high=100, size=(5, 5))

array([[98,  6, 26, 13, 75],
       [58, 25,  3, 74, 75],
       [61, 77, 83, 57, 94],
       [32, 10,  6, 75, 18],
       [ 3, 77, 17, 43, 16]])